name: Swift Package Manager

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]
  workflow_call:
    inputs:
      swift-version:
        required: false
        type: string
        default: '6.0.0'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Swift
      uses: fwal/setup-swift@v2
      with:
        swift-version: ${{ inputs.swift-version }}

    - name: Generate Package.resolved (if missing)
      run: swift package resolve

    - name: Cache Swift Build
      uses: actions/cache@v3
      with:
        path: |
          .build
          .swiftpm
        key: SPM-${{ runner.os }}-swift-${{ inputs.swift-version }}-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          SPM-${{ runner.os }}-swift-${{ inputs.swift-version }}-
          SPM-${{ runner.os }}-

    - name: Cache Status Check
      run: |
        if [ -d ".build" ]; then
          echo "Cache restored successfully ✅"
        else
          echo "Cache not found ❌"
        fi

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
